refactor check

diff --git a/bin/shipment-check b/bin/shipment-check
--- a/bin/shipment-check
+++ b/bin/shipment-check
@@ -9,42 +9,43 @@ fi
 usage_running() {
   cat <<-EOF
 
-  Usage: shipment check [options]
+  Usage: shipment check [options] [id]
 
-  Deploy options:
+  Options:
 
-    -i                   check a specific container id
-    -n                   check all apps by name
+    Optional:
+    -p,--port <port>              port to check [default: 5000]
 
 EOF
 }
 
 main() {
-  local id=0
-  local name=""
   local port=5000
-  while getopts "i:n:p:" OPTION "$@"; do
-    case $OPTION in
-      i) id=$OPTARG;;
-      n) name="$OPTARG";;
-      p) port="$OPTARG";;
+
+  while (( "$#" )); do
+    case "$1" in
+      -p|--port)
+        port=$2
+        shift 2
+        ;;
+      --) # end argument parsing
+        shift
+        break
+        ;;
+      -*|--*=) # unsupported flags
+        log "Error: Unsupported flag $1" >&2
+        exit 1
+        ;;
+      *) # preserve positional arguments
+        params+=($1)
+        shift
+        ;;
     esac
   done
+  # set positional arguments in their proper place
+  eval set -- "$params"
+  local id=${params[0]}
 
-  if [[ -n "$name" ]]; then
-    log "Checking $name"
-    local running=$(shipment running -i -a -n $name)
-    #read config
-    local conf_file="$APPSPATH/$name/.shipment"
-    if [[ -e "$conf_file" ]]; then
-      source $conf_file
-    fi
-    local port=${SHIPMENT_PORT:-5000}
-    for i in ${running[@]}; do
-      sudo shipment check -i $i -p $port
-    done
-    exit 0
-  fi
   local ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $id)
   log "Checking $id on port $port"
 
