more refactoring

diff --git a/bin/shipment b/bin/shipment
--- a/bin/shipment
+++ b/bin/shipment
@@ -4,7 +4,9 @@ set -e
 VERSION="0.18.2"
 BRIDGE_IP=172.17.42.1
 SHIPMENTPATH=/var/shipment
+SHIPMENTCONFIG=$SHIPMENTPATH/config
 APPSPATH=$SHIPMENTPATH/apps
+SCRIPT=$0
 
 DIR=$(dirname $0)
 
@@ -55,6 +57,18 @@ get_commit() {
 }
 
 readconfig() {
+  local name=$1
+  if [[ ! -f $SHIPMENTCONFIG/$name ]]; then
+    log "$name config not found. Must call shipment create first"
+    exit 1
+  fi
+
+  local configstr=$(cat $SHIPMENTCONFIG/$name)
+
+  parseconfig $configstr
+}
+
+parseconfig() {
   port=5000
   env=()
   volume=()
@@ -67,6 +81,10 @@ readconfig() {
         ;;
       -h|--host)
         host=$2
+        shift 2
+        ;;
+      -p|--port)
+        port=$2
         shift 2
         ;;
       -e|--env)
@@ -90,24 +108,28 @@ readconfig() {
         exit 1
         ;;
       *) # preserve positional arguments
-        params="$params $1"
+        params+=($1)
         shift
         ;;
     esac
   done
   # set positional arguments in their proper place
   eval set -- "$params"
-  name=$params
+  if [[ ${#params[@]} == 0 ]]; then
+    log "Must pass in name of app"
+    exit 1
+  fi
+  name=${params[0]}
 }
 
 writeconfig() {
-  if [[ ! -d $SHIPMENTPATH/config ]]; then
-    mkdir -p $SHIPMENTPATH/config
+  if [[ ! -d $SHIPMENTCONFIG ]]; then
+    mkdir -p $SHIPMENTCONFIG
   fi
 
   local name=$1
   shift
-  echo $@ > $SHIPMENTPATH/config/$name
+  echo $@ > $SHIPMENTCONFIG/$name
 
 }
 
diff --git a/bin/shipment-deploy b/bin/shipment-deploy
--- a/bin/shipment-deploy
+++ b/bin/shipment-deploy
@@ -15,8 +15,74 @@ if [ "$#" == 0 ]; then
   exit
 fi
 
-
 main() {
+
+  local scale=1
+  local check=1
+  local branch="master"
+  local params=()
+  while (( "$#" )); do
+    case "$1" in
+      -s|--scale)
+        scale=$2
+        shift 2
+        ;;
+      --nocheck)
+        check=0
+        shift 2
+        ;;
+      -b|--branch)
+        branch=$2
+        shift 2
+        ;;
+      --) # end argument parsing
+        shift
+        break
+        ;;
+      -*|--*=) # unsupported flags
+        log "Error: Unsupported flag $1" >&2
+        exit 1
+        ;;
+      *) # preserve positional arguments
+        params+=($1)
+        shift
+        ;;
+    esac
+  done
+  # set positional arguments in their proper place
+  eval set -- "$params"
+  local name=${params[0]}
+
+  readconfig $name
+
+  #build
+  log "building $name ($branch)"
+  docker build -t "shipment/$name:$branch" $repo
+
+  #run
+  log "running new container(s)..."
+  local new_ids=()
+  for i in $(seq 1 $scale); do
+    local id=$(exec $SCRIPT run $name --branch $branch)
+    new_ids+=($id)
+  done
+
+  #check
+  if [[ "$check" == 1 ]]; then
+    for i in ${new_ids[@]}; do
+      shipment check --id $i --port $port
+    done
+  fi
+  #update loadbalancer
+  #stop old containers
+  #update loadbalancer
+  #remove old containers
+  #clean old images
+
+
+}
+
+mainold() {
   local scale=1;
   local nocheck=0;
 
diff --git a/bin/shipment-run b/bin/shipment-run
--- a/bin/shipment-run
+++ b/bin/shipment-run
@@ -7,19 +7,36 @@ if [ "$1" == "_description" ]; then
 fi
 
 main() {
-  local name=$1
-  local commit=$(get_commit $name)
 
-  #read config
-  local conf_file="$APPSPATH/$name/.shipment"
-  if [[ -e "$conf_file" ]]; then
-    source $conf_file
-  fi
-  local url=$SHIPMENT_URL
-  local dockerargs=$SHIPMENT_DOCKERARGS
-  local port=${SHIPMENT_PORT:-5000}
+  local branch="master"
+  local params=()
+  while (( "$#" )); do
+    case "$1" in
+      -b|--branch)
+        branch=$2
+        shift 2
+        ;;
+      --) # end argument parsing
+        shift
+        break
+        ;;
+      -*|--*=) # unsupported flags
+        log "Error: Unsupported flag $1" >&2
+        exit 1
+        ;;
+      *) # preserve positional arguments
+        params+=($1)
+        shift
+        ;;
+    esac
+  done
+  # set positional arguments in their proper place
+  eval set -- "$params"
+  local name=${params[0]}
 
-  local container_id=$(sudo docker run -d -p $port -e VIRTUAL_HOST=$url -e PORT=$port $dockerargs shipment/$name:$commit)
+  readconfig $name
+
+  local container_id=$(docker run -d -p $port -e VIRTUAL_HOST=$host -e PORT=$port shipment/$name:$branch)
   echo $container_id
 }
 main "$@"
